Company
yanagisawahidetoshi/attendance-api pull request #5
Opened 2018-06-18 14:02 UTC by yanagisawahidetoshi

2018-06-21 14:43 UTC, fruwe requested changes

2018-06-21 14:43 UTC, fruwe commented on app/controllers/v1/companies_controller.rb
> +    before_action :checkAuth
rubyなのでcamelCaseではなくunderscoreを使った方がいいです

2018-06-21 14:43 UTC, fruwe commented on app/controllers/v1/companies_controller.rb
> +      total = Company.page.total_pages
total_pagesはテーブルに対してcountを発行するために大量データがありえるテーブルの場合にはご注意

2018-06-21 14:43 UTC, fruwe commented on spec/models/company_spec.rb
>      company = build(:company, address: 'EPaXx25VwzLXMTSmrwERG9h-ficJEgVfUXbtHZMi_PnYEjwBT4Wx7R_EEtMPEEpzH8Rzz4jytVzFaaeFVMAcAWWDwrVM5pd5ZF8sPEeSdf64QG4z4cCpZUDYbe5rZ8Y9dXs_DFMjV5H4xM3-kMgjiSSB4ca-YSU
"a" * 65 の方が読みやすいかもしれない

2018-06-21 14:43 UTC, fruwe commented on spec/models/company_spec.rb
> +    expect(company.errors[:zip]).to include('は8文字以内で入力してください')
zip はフォーマットも確認した方がいいです　(例：554-34-2)

2018-06-21 14:43 UTC, fruwe commented on spec/models/company_spec.rb
> -    expect(company.errors[:tel]).to include('is too long (maximum is 13 characters)')
海外の会社はありえない仕組みですね？あと、フォーマットも確認した方がいいです　(例：080-080--1234)

2018-06-21 14:43 UTC, fruwe commented on spec/factories/users.rb
> +    authority 3
マジックナンバー

2018-06-21 14:43 UTC, fruwe commented on spec/factories/users.rb
> +      authority 1
マジックナンバー

2018-06-21 14:43 UTC, fruwe commented on spec/factories/companies.rb
> +    tel {Faker::PhoneNumber.phone_number}
{x}か{ x }に統一した方がいい。rubocopを使えば？

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +    let(:companies) { create_list(:company, 100) }
ある特定なletを一つのテストでしか使わない場合には
```
describe do
  it '正常にレスポンスを返すこと' do
  end

  context '多数の会社' do
    let(:companies) { create_list(:company, 100) }

    it 'companyが取得されていること' do
    end
  end
end
```

の方がいい気がします

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        companies
100組織を作るのは思い処理です。per_pageを3にして4組織を作った方がいい気がします

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        expect(response.body).to include '会社名を入力してください'
データが追加されていないことを確認した方がいい。

例：
```
expect { post(:create) }.to change { Company.count }.by(0)
```

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        companyObj = Company.first
camelCase -> underscore

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        companyObj = Company.first
companyをそのまま使って下さい。
controller側でcompanyがSQLで取得されますので特に心配が必要ない。
しかしその場合にはputの後に company.reloadをしないとcompanyが更新されない

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        companyObj = Company.first
そもそもcompanyObjが不要です。

params = {id: company.id, name: 'HOGEHOGEHOGEHOG'}でいいと思います

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        companyObj = Company.last
上記と同様

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        delete :delete
上記と同様にchange matcherを使った方がいい

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        delete :delete, params: params
上記と同様、companyObjが不要、change matcherを使った方がいい

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +        delete :delete, params: params
上記と同様

2018-06-21 14:43 UTC, fruwe commented on spec/controllers/v1/companies_controller_spec.rb
> +      request.headers['Authorization'] = User.first.access_token
一番目のユーザのアクセストークンを使うと１番目のユーザの一覧が返却されないはずですか？それがなぜそうになるのは理解しずらい。
また、存在しないトークン、またトークンなしのテストも必要

2018-06-21 14:43 UTC, fruwe commented on app/controllers/v1/companies_controller.rb
> +      unless current_user[:authority] == 1
マジックナンバー。。。
1と謎の3もあります。
しかも、カラムのNULL制限がないので、nilもありえます。有効な値をもっとはっきりに決めた方がいい。。

この二つはおすすめします：
http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html
https://github.com/iangreenleaf/native_enum (私のおすすめですが、最近メンテされていないようです)

2018-06-21 14:43 UTC, fruwe commented on app/controllers/v1/companies_controller.rb
> +      render
不要

2018-06-21 14:43 UTC, fruwe commented on app/controllers/v1/companies_controller.rb
> +    def checkAuth
checkAuthは共通なロジックならApplicationControllerに入れた方がいい
多数のコントローラを作るなら
https://github.com/varvet/pundit
を使った方が楽

2018-06-26 03:49 UTC, yanagisawahidetoshi commented on spec/controllers/v1/companies_controller_spec.rb
> +      request.headers['Authorization'] = User.first.access_token
これってどういう意味でしょう？
@fruwe

2018-07-24 09:28 UTC, merged